services:
  app:
    container_name: Aapplication_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_PORT: "8080"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      JWT_SECRET: "${JWT_SECRET}"
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME}"
      MIGRATIONS_PATH: /app/database/migrations
    volumes:
      - .:/app
      - /app/tmp
    networks:
      - app-network
    depends_on:
      - postgresDB
  postgresDB:
    image: postgres:latest
    container_name: Database_container
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
