basePath: /api
definitions:
  models.Users:
    properties:
      address:
        type: string
      contact:
        type: integer
      email:
        type: string
      name:
        type: string
      password:
        type: string
      status:
        type: boolean
      uuid:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a WORK store.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: pov_Golang API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Get the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - Health
  /user:
    post:
      consumes:
      - application/json
      description: Registers a new user and returns a JWT token
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.Users'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: '{\"error\": \"invalid request body\"}'
        "500":
          description: '{\"error\": \"something went wrong\"}'
      summary: Create a new user
      tags:
      - Public
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
